dbt_profiles:
  target: default  # Set the target environment to prod
  outputs:
    default:  # Connection details for your dev environment
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_DEV') }}"
      user: "{{ env_var('SNOWFLAKE_USER_DEV') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD_DEV') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE_DEV') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE_DEV') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE_DEV') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA_DEV') }}"
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt
    dev:  # Connection details for your dev environment
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_DEV') }}"
      user: "{{ env_var('SNOWFLAKE_USER_DEV') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD_DEV') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE_DEV') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE_DEV') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE_DEV') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA_DEV') }}"
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt
    prod:  # Connection details for your production environment
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_PROD') }}"
      user: "{{ env_var('SNOWFLAKE_USER_PROD') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD_PROD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE_PROD') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE_PROD') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE_PROD') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA_PROD') }}"
      threads: 4  # You might want to adjust the number of threads for production
      client_session_keep_alive: False
      query_tag: dbt
